### ISSUE TITLE
use Oracle Java by default

### ISSUE THREAD

**Issue by afeld** [GSA/jenkins-deploy#11]

**Comment by kishorebabu12** [comment]
Can we look at Open JDK/JRE 8 as a possible alternate?

**Comment by afeld** [comment]
@jerodweaver Is it ok for us to use OpenJDK, or do we need to use the Oracle JDK?

**Comment by jerodweaver** [comment]
@afeld What is the issue with using the official Oracle JDK?  I assume maybe Jenkins is deployed with something other than the official Oracle JDK by default?

**Comment by afeld** [comment]
Yes, OpenJDK is a bit easier to use because

* It's what the Jenkins Ansible role I'm using uses by default
* It doesn't require license acceptance to download, making automation easier

Not a huge deal - mostly just curious.

**Comment by jerodweaver** [comment]
@afeld The simple answer is that since OpenJDK isn't on the IT Standards list, that you would need to use the official oracle JDK.
