### ISSUE TITLE
ensure that Jenkins does proper logging required by GSA

### ISSUE THREAD

**Issue by afeld** [GSA/jenkins-deploy#34]

**Comment by JJediny** [comment]
Happy to parse out our fluentd agent install into its own repo w/ secops target? 

```
<source>
  type tail
  format multiline
  format_firstline /^\w+\s\d+,\s\d+/
  format1 /(?<message>.*)/
  path /var/log/jenkins/jenkins.log
  read_from_head true
  tag jenkins
</source>
```

**Comment by afeld** [comment]
[D2D has been using RSYSLOG](https://docs.google.com/document/d/12K4OehW_KmW5iZcv9TcA6As9K17aENxIAXsI4xrIPjw/edit) as part of our base image...not sure if there's major benefit for one vs. the other, or if it's a bad idea to mix them?

/cc @dvvolodin

**Comment by afeld** [comment]
Also presumably need to send logs for the jobs...

https://wiki.jenkins.io/display/JENKINS/Logging#Logging-MakinglogsavailableoutsideofthewebUI

**Comment by afeld** [comment]
* [Access logging](https://wiki.jenkins.io/pages/viewpage.action?pageId=74875442)
* https://www.cloudbees.com/blog/best-practices-setting-jenkins-auditing-and-compliance
* [rsyslog config example](https://gist.github.com/garlandkr/4512815)
* [Syslog logger plugin](https://wiki.jenkins.io/plugins/servlet/mobile#content/view/72417840)

**Comment by afeld** [comment]
* [x] Ensure that Jenkins system logs are making it to syslog
* [x] Ensure access logging is enabled/present
* [ ] ~~Ensure that job logs are making it to syslog~~

**Comment by JJediny** [comment]
https://wiki.jenkins.io/display/JENKINS/FluentD+Plugin... 

**For testing/consideration:**
rsyslog may alter/manipulate the synthax of the java output
